version: "3.9"

services:
  search-server:
    build: .
    image: search-app
    ports:
        - 3001:3001
    environment:
        - PORT=3001
        - POSTGRES_DB=search-app
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - DB_HOST=search-db
    depends_on:
        search-db:
          condition: service_healthy
  search-db:
    image: postgres
    environment:
      - POSTGRES_DB=search-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20